# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colab.

# Static Array (Numpy)
"""

import time
import numpy as np

# --- 作業準備：建立 500 萬筆測試資料 ---
print("正在產生 500 萬筆測試資料，請稍候...")
num_elements = 5000000
python_list = [1.5] * num_elements       # 傳統 Python List
numpy_array = np.array(python_list)      # 連續記憶體的 Numpy Array
print("資料產生完畢！\n" + "-"*30)

# ==========================================
# 測試 1：計算總和
# ==========================================
print("【測試 1：500萬筆資料加總計算】")

# 1-1. Python List 總和
start_time = time.time()

# TODO 1-1: 請使用 Python for loop 語法，計算 python_list 的總和，並存入 list_sum 變數
list_sum = 0
for data in python_list:
    list_sum += data

end_time = time.time()
print(f"Python List 加總耗時: {end_time - start_time:.5f} 秒")

# 1-2. Numpy Array 總和
start_time = time.time()

# TODO 1-2: 請使用 Numpy 的 .sum() 方法，計算 numpy_array 的總和，並存入 np_sum 變數
np_sum = numpy_array.sum()

end_time = time.time()
print(f"Numpy Array 加總耗時: {end_time - start_time:.5f} 秒")
print("-"  * 30)

# ==========================================
# 測試 2：新增資料 (彈性空間的代價)
# ==========================================
print("【測試 2：新增 100 萬筆新客戶資料】")
new_customers = [2.0] * 1000000

# 2-1. Python List 新增資料 (動態擴容)
start_time = time.time()

# TODO 2-1: 請使用 Python list 的 .append() 搭配 for loop，將 new_customers 加入 python_list 中
for customer in new_customers:
    python_list.append(customer)

end_time = time.time()
print(f"Python List 新增資料耗時: {end_time - start_time:.5f} 秒")

# 2-2. Numpy Array 新增資料 (強迫搬家)
start_time = time.time()

# TODO 2-2: Numpy 預設大小固定，無法直接 append。
#     - 請使用 np.append(舊陣列, 新資料) 來產生一個「全新」的陣列，並重新指派給 numpy_array 變數。
numpy_array = np.append(numpy_array, new_customers)

end_time = time.time()
print(f"Numpy Array 新增資料(被迫搬家)耗時: {end_time - start_time:.5f} 秒")

# 3. 最後用註解解釋以下
#     3-1. 為什麼 1-1 和 1-2 差這麼多，底層是什麼原因 ?
# Ans 3-1:
# Python List 使用 for loop 時，是一個一個 Python 物件慢慢取出再加總，
# 每次迴圈都需要經過 Python 解釋器處理，所以速度比較慢。
# Numpy Array 的資料存在連續記憶體中，而且底層是 C 語言實作，
# 可以使用向量化運算一次處理大量資料，所以速度快很多。

#     3-2. 為什麼 2-1 和 2-2 差這麼多，底層是什麼原因 ?
# Ans 3-2:
# Python List 是 Dynamic Array，append 時通常可以直接加到尾端，
# 雖然偶爾需要擴容搬家，但平均下來 append 仍接近 O(1)。
# Numpy Array 是 Static Array，大小固定，不能真的原地 append。
# np.append 會建立一個新的陣列，然後把舊資料和新資料全部複製過去，
# 所以成本比較高。

#     3-3. 描述 2-2 和我們上課的什麼觀念有關 (請詳答) ?
# Ans 3-3:
# 2-2 和上課提到的 Static Array 固定大小、搬家問題有關。
# Numpy Array 的記憶體是連續配置，所以運算和隨機存取很快，
# 但也因為大小固定，新增資料時無法像 List 一樣彈性擴充。
# 當需要 append 新資料時，Numpy 必須重新建立更大的連續記憶體空間，
# 再把原本的資料複製過去，這就是 Array 的搬家問題，也就是 O(N) 的代價。


"""# Linked List (Deque)"""

import time
from collections import deque

# --- 作業準備：建立 30 萬筆排隊資料 ---
print("正在建立 30 萬人的排隊系統，請稍候...")
queue_size = 300000
python_list_queue = list(range(queue_size))
linked_list_queue = deque(range(queue_size))
print("系統建立完畢！\n" + "-"*30)

# ==========================================
# 測試 4：VIP 頭部插隊 (平移地獄 vs. 指標牽手)
# ==========================================
print("【測試 1：1000 位 VIP 進入隊伍最前面】")
insert_count = 1000

# 4-1. Python List (Array) 的頭部插隊
start_time = time.time()
for i in range(insert_count):
    # TODO 4-1: 請使用 .insert() 方法，將字串 "VIP" 插入到 python_list_queue 的最前面 (index 0)
    python_list_queue.insert(0, "VIP")

end_time = time.time()
print(f"Python List (O(N) 平移) 耗時: {end_time - start_time:.5f} 秒")

# 4-2. Deque (Linked List) 的頭部插隊
start_time = time.time()
for i in range(insert_count):
    # TODO 4-2: 請使用 deque 專屬的頭部方法，將字串 "VIP" 放入 linked_list_queue 最前面
    linked_list_queue.appendleft("VIP")

end_time = time.time()
print(f"Deque (O(1) 瞬間牽手) 耗時: {end_time - start_time:.5f} 秒")
print("-"  * 30)

# ==========================================
# 測試 5：行銷部抽獎 (Random Access 隨機存取)
# ==========================================
print("【測試 2：行銷部隨機查詢第 15 萬號排隊者 1000 次】")
target_index = 150000
query_count = 1000

# 5-1. Python List 找特定位置
start_time = time.time()
for _ in range(query_count):
    # TODO 5-1: 請直接用中括號 [] 取出 python_list_queue 第 target_index 個位置的資料，存入變數 lucky_guy
    lucky_guy = python_list_queue[target_index]

end_time = time.time()
print(f"Python List (O(1)) 耗時: {end_time - start_time:.5f} 秒")

# 5-2. Deque 找特定位置
start_time = time.time()
for _ in range(query_count):
    # TODO 5-2: 請直接用中括號 [] 取出 linked_list_queue 第 target_index 個位置的資料，存入變數 lucky_guy
    lucky_guy = linked_list_queue[target_index]

end_time = time.time()
print(f"Deque (O(N) 從頭慢慢找) 耗時: {end_time - start_time:.5f} 秒")

# 6. 最後用註解解釋以下
#     6-1. 為什麼 4-1 和 4-2 差這麼多，底層是什麼原因 ?
# Ans 6-1:
# Python List 在最前面 insert(0, "VIP") 時，原本所有資料都必須往後移一格，
# 因此資料越多，搬移成本越高，時間複雜度是 O(N)。
# Deque 是雙向佇列，適合在頭部或尾部新增、刪除資料。
# appendleft 只需要調整頭部的指標，不需要搬移所有資料，
# 所以時間複雜度是 O(1)。

#     6-2. 為什麼 5-1 和 5-2 差這麼多，底層是什麼原因 ?
# Ans 6-2:
# Python List 的底層是連續記憶體，可以透過 index 直接計算位置，
# 所以 python_list_queue[target_index] 是 O(1)。
# Deque 的底層概念接近 Linked List，資料不是完整連續排列，
# 查詢中間位置時需要從頭或尾一路找過去，
# 所以 linked_list_queue[target_index] 的時間複雜度接近 O(N)。